# Generated by Django 3.2.8 on 2021-11-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
