# Generated by Django 3.2.8 on 2021-11-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverImage',
            field=models.ImageField(default='posts/blog1.jpg', upload_to='posts/'),
        ),
    ]
