# Generated by Django 3.2.8 on 2021-11-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_user_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-dateCreated']},
        ),
    ]
