# Generated by Django 3.2.8 on 2021-11-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverImage',
            field=models.ImageField(default='posts/blog2.jpg', upload_to='posts/'),
        ),
    ]
